- repo: git://github.com/pecigonzalo/pre-commit-shfmt
  sha: master
  hooks:
    - id: shell-fmt

- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.7.1
  hooks:
    - id: check-yaml
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
